modLoader = "javafml"
loaderVersion = "[${neoforge_loader_version},)"
license = "GPL3"

[[mods]]
modId = "kubeutils"
version = "${version}"
displayName = "KubeUtils"
authors="ErrorMikey"
description = '''
Provides extra methods and tools to the standard KubeJS mod
'''

[[dependencies.kubeutils]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kubeutils]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kubeutils]]
modId = "kubejs"
mandatory = true
versionRange = "[${kubejs_version},)"
ordering = "NONE"
side = "BOTH"
