modLoader = "javafml"
loaderVersion = "[${neoforge_loader_version},)"
license = "GPL3"

[[mods]]
modId = "kubeutils"
version = "${version}"
displayName = "KubeUtils"
authors="ErrorMikey"
description = '''
Provides extra methods and tools to the standard KubeJS mod
'''

[[dependencies.kubeutils]]
modId = "neoforge"
required = true
versionRange = "[${neoforge_base_two},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kubeutils]]
modId = "minecraft"
required = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kubeutils]]
modId = "kubejs"
required = true
versionRange = "[${kubejs_version},)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "kubeutils.mixins.json"
